[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.119.0",
    "psycopg2-binary>=2.9.11",
<<<<<<< HEAD
    "pydantic>=2.12.0",
=======
>>>>>>> e38a67a9ed2823f4e0900033cd9520f9fa31fe61
    "python-dotenv>=1.1.1",
    "sqlalchemy>=2.0.44",
    "uvicorn>=0.37.0",
]
